### ISSUE TITLE
Plug-in won't compile on MacOS 10.14.6

### ISSUE THREAD

**Issue by pcgeek86** [feuerbach/noise-gate#1]
I'm having trouble compiling this plugin on MacOS. Here's what I've done so far:

1. Clone repository
1. Install boost library from Homebrew: `brew install boost`
1. Grab `ladspa.h` and placed into project folder
1. Changed `#include <ladspa.h>` to `#include "ladspa.h"` in all files
1. Ran `make`

Here's the output from `make`:

```
c++ -Wall -pedantic -fPIC -DPIC -O2  -o ng.o -c ng.cpp
ng.cpp:21:19: error: function definition does not declare parameters
    unsigned long n_samples {0};
                  ^
ng.cpp:24:32: error: use of undeclared identifier 'n_samples'; did you mean '__sample'?
      return buf[buf.size() - (n_samples - index)];
                               ^~~~~~~~~
                               __sample
/Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:3128:17: note: '__sample' declared here
_SampleIterator __sample(_PopulationIterator __first,
                ^
ng.cpp:24:32: error: reference to overloaded function could not be resolved; did you mean to call it?
      return buf[buf.size() - (n_samples - index)];
                               ^~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:3128:17: note: possible target for call
_SampleIterator __sample(_PopulationIterator __first,
                ^
ng.cpp:34:53: error: use of undeclared identifier 'n_samples'; did you mean 'sample'?
      while (!indices.empty() && indices.front() <= n_samples - window_size) {
                                                    ^~~~~~~~~
                                                    sample
ng.cpp:29:27: note: 'sample' declared here
    void push(LADSPA_Data sample) {
                          ^
ng.cpp:37:25: error: use of undeclared identifier 'n_samples'; did you mean 'sample'?
      indices.push_back(n_samples++);
                        ^~~~~~~~~
                        sample
ng.cpp:29:27: note: 'sample' declared here
    void push(LADSPA_Data sample) {
                          ^
ng.cpp:54:19: error: function definition does not declare parameters
    unsigned long nonsilent_samples {0};
                  ^
ng.cpp:66:9: error: use of undeclared identifier 'nonsilent_samples'
        nonsilent_samples -= buf.front();
        ^
ng.cpp:69:7: error: use of undeclared identifier 'nonsilent_samples'
      nonsilent_samples += new_nonsilent;
      ^
ng.cpp:73:14: error: use of undeclared identifier 'nonsilent_samples'
      return nonsilent_samples / sample_rate;
             ^
ng.cpp:92:29: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
    const LADSPA_Data floor = 1e-4; // -80 dB
                            ^
ng.cpp:95:30: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
    LADSPA_Data current_coef = 1;
                             ^
ng.cpp:97:10: error: function definition does not declare parameters
    bool rising {true};
         ^
ng.cpp:101:38: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
    long unsigned samples_since_open = 0;
                                     ^
ng.cpp:114:9: error: use of undeclared identifier 'rising'
        rising = true;
        ^
ng.cpp:118:11: error: use of undeclared identifier 'rising'
          rising = false;
          ^
ng.cpp:121:11: error: use of undeclared identifier 'rising'; did you mean 'isinf'?
      if (rising) {
          ^~~~~~
          isinf
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:497:1: note: 'isinf' declared here
isinf(long double __lcpp_x) _NOEXCEPT { return __libcpp_isinf(__lcpp_x); }
^
ng.cpp:121:11: warning: address of function 'isinf' will always evaluate to 'true' [-Wpointer-bool-conversion]
      if (rising) {
      ~~  ^~~~~~
ng.cpp:121:11: note: prefix with the address-of operator to silence this warning
      if (rising) {
          ^
          &
ng.cpp:144:48: error: a space is required between consecutive right angle brackets (use '> >')
  unique_ptr<boost::circular_buffer<LADSPA_Data>> buf;
                                               ^~
                                               > >
ng.cpp:169:19: error: use of undeclared identifier 'make_unique'
      ns_window = make_unique<NonSilenceWindow>(window_samples,
                  ^
ng.cpp:169:31: error: 'NonSilenceWindow' does not refer to a value
      ns_window = make_unique<NonSilenceWindow>(window_samples,
                              ^
ng.cpp:48:7: note: declared here
class NonSilenceWindow {
      ^
ng.cpp:169:49: warning: expression result unused [-Wunused-value]
      ns_window = make_unique<NonSilenceWindow>(window_samples,
                                                ^~~~~~~~~~~~~~
ng.cpp:170:62: warning: expression result unused [-Wunused-value]
                                                 sample_rate * 5e-3,
                                                 ~~~~~~~~~~~ ^ ~~~~
ng.cpp:171:50: warning: expression result unused [-Wunused-value]
                                                 sample_rate,
                                                 ^~~~~~~~~~~
ng.cpp:175:19: error: use of undeclared identifier 'make_unique'
      sm_window = make_unique<SmoothingWindow>(sm_window_size);
                  ^
ng.cpp:175:31: error: 'SmoothingWindow' does not refer to a value
      sm_window = make_unique<SmoothingWindow>(sm_window_size);
                              ^
ng.cpp:90:7: note: declared here
class SmoothingWindow {
      ^
ng.cpp:178:13: error: use of undeclared identifier 'make_unique'
      buf = make_unique<boost::circular_buffer<LADSPA_Data>>(latency_samples);
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
7 warnings and 20 errors generated.
make: *** [ng.o] Error 1
```

**Comment by UnkindPartition** [comment]
Hey @pcgeek86, I'm sorry, somehow I totally missed this issue when it was filed.

Can you find out what c++ compiler/version (`c++ --version`) and boost version (somehow via homebrew, I guess?) you have on your system?

**Comment by danliebke** [comment]
Hi @feuerbach. I'm having the same compile problem. My c++ version is Apple clang version 11.0.3 (clang-1103.0.32.59). My boost version is 1.72. Any help would be appreciated - the idea of this noise-gate plugin sounds great. (And hopefully sounds great too.)

**Comment by danliebke** [comment]
My MacOS is 10.15.4, by the way.

**Comment by UnkindPartition** [comment]
@danliebke unfortunately, I only have access to clang 9.0.1, and I cannot reproduce this. I made a couple of changes, please let me know if any errors still remain.

**Comment by danliebke** [comment]
It seems to be getting closer but there is still one error at the end of the compile. 

Here's the output from make:

`cc   ng.o   -o ng
Undefined symbols for architecture x86_64:
  "registerNewPluginDescriptor(CMT_Descriptor*)", referenced from:
      init_noise_gate() in ng.o
  "CMT_Descriptor::addPort(int, char const*, int, float, float)", referenced from:
      init_noise_gate() in ng.o
  "CMT_Descriptor::CMT_Descriptor(unsigned long, char const*, int, char const*, char const*, char const*, CMT_ImplementationData*, void* (*)(_LADSPA_Descriptor const*, unsigned long), void (*)(void*), void (*)(void*, unsigned long), void (*)(void*, unsigned long), void (*)(void*, float), void (*)(void*))", referenced from:
      init_noise_gate() in ng.o
  "std::logic_error::what() const", referenced from:
      vtable for boost::exception_detail::error_info_injector<std::length_error> in ng.o
      vtable for boost::wrapexcept<std::length_error> in ng.o
      construction vtable for boost::exception_detail::clone_impl<boost::wrapexcept<std::length_error>::error_info_injector<std::length_error> >-in-boost::wrapexcept<std::length_error> in ng.o
      vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> > in ng.o
  "std::logic_error::logic_error(char const*)", referenced from:
      NoiseGate::run(unsigned long) in ng.o
      std::length_error::length_error(char const*) in ng.o
  "std::logic_error::logic_error(std::logic_error const&)", referenced from:
      boost::wrapexcept<boost::exception_detail::remove_error_info_injector<std::length_error>::type> boost::exception_detail::enable_both<std::length_error>(std::length_error const&) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_impl(boost::exception_detail::error_info_injector<std::length_error> const&) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> > const&, boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_tag) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> > const&) in ng.o
  "std::length_error::~length_error()", referenced from:
      NoiseGate::run(unsigned long) in ng.o
      std::__1::__throw_length_error(char const*) in ng.o
  "std::length_error::~length_error()", referenced from:
      boost::wrapexcept<boost::exception_detail::remove_error_info_injector<std::length_error>::type> boost::exception_detail::enable_both<std::length_error>(std::length_error const&) in ng.o
      boost::wrapexcept<std::length_error>::~wrapexcept() in ng.o
      boost::exception_detail::error_info_injector<std::length_error>::~error_info_injector() in ng.o
      boost::exception_detail::error_info_injector<std::length_error>::~error_info_injector() in ng.o
      non-virtual thunk to boost::exception_detail::error_info_injector<std::length_error>::~error_info_injector() in ng.o
      non-virtual thunk to boost::exception_detail::error_info_injector<std::length_error>::~error_info_injector() in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_impl(boost::exception_detail::error_info_injector<std::length_error> const&) in ng.o
      ...
  "std::terminate()", referenced from:
      ___clang_call_terminate in ng.o
  "typeinfo for std::length_error", referenced from:
      std::__1::__throw_length_error(char const*) in ng.o
      typeinfo for boost::exception_detail::error_info_injector<std::length_error> in ng.o
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for boost::exception in ng.o
      typeinfo for boost::exception_detail::clone_base in ng.o
      typeinfo for CMT_PluginInstance in ng.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for boost::wrapexcept<std::length_error> in ng.o
      typeinfo for NoiseGate in ng.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__vmi_class_type_info", referenced from:
      typeinfo for boost::exception_detail::error_info_injector<std::length_error> in ng.o
      typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> > in ng.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for std::length_error", referenced from:
      NoiseGate::run(unsigned long) in ng.o
      std::length_error::length_error(char const*) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_impl(boost::exception_detail::error_info_injector<std::length_error> const&) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> > const&, boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_tag) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> > const&) in ng.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator delete[](void*)", referenced from:
      CMT_PluginInstance::~CMT_PluginInstance() in ng.o
      CMT_PluginInstance::~CMT_PluginInstance() in ng.o
      NoiseGate::~NoiseGate() in ng.o
  "operator delete(void*)", referenced from:
      NoiseGate::run(unsigned long) in ng.o
      init_noise_gate() in ng.o
      void* CMT_Instantiate<NoiseGate>(_LADSPA_Descriptor const*, unsigned long) in ng.o
      boost::exception_detail::error_info_injector<std::length_error>::~error_info_injector() in ng.o
      non-virtual thunk to boost::exception_detail::error_info_injector<std::length_error>::~error_info_injector() in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::~clone_impl() in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone() const in ng.o
      ...
  "operator new[](unsigned long)", referenced from:
      void* CMT_Instantiate<NoiseGate>(_LADSPA_Descriptor const*, unsigned long) in ng.o
  "operator new(unsigned long)", referenced from:
      NoiseGate::run(unsigned long) in ng.o
      init_noise_gate() in ng.o
      void* CMT_Instantiate<NoiseGate>(_LADSPA_Descriptor const*, unsigned long) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone() const in ng.o
      virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::clone() const in ng.o
      std::__1::deque<unsigned long, std::__1::allocator<unsigned long> >::__add_back_capacity() in ng.o
      std::__1::__split_buffer<unsigned long*, std::__1::allocator<unsigned long*> >::push_back(unsigned long*&&) in ng.o
      ...
  "___cxa_allocate_exception", referenced from:
      void boost::throw_exception<std::length_error>(std::length_error const&) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::rethrow() const in ng.o
      virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::rethrow() const in ng.o
      std::__1::__throw_length_error(char const*) in ng.o
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in ng.o
  "___cxa_free_exception", referenced from:
      void boost::throw_exception<std::length_error>(std::length_error const&) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::rethrow() const in ng.o
      virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::rethrow() const in ng.o
      std::__1::__throw_length_error(char const*) in ng.o
  "___cxa_pure_virtual", referenced from:
      vtable for boost::exception in ng.o
      vtable for boost::exception_detail::clone_base in ng.o
  "___cxa_throw", referenced from:
      void boost::throw_exception<std::length_error>(std::length_error const&) in ng.o
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::rethrow() const in ng.o
      virtual thunk to boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >::rethrow() const in ng.o
      std::__1::__throw_length_error(char const*) in ng.o
  "___gxx_personality_v0", referenced from:
      NoiseGate::run(unsigned long) in ng.o
      init_noise_gate() in ng.o
      void* CMT_Instantiate<NoiseGate>(_LADSPA_Descriptor const*, unsigned long) in ng.o
      void boost::throw_exception<std::length_error>(std::length_error const&) in ng.o
      boost::wrapexcept<boost::exception_detail::remove_error_info_injector<std::length_error>::type> boost::exception_detail::enable_both<std::length_error>(std::length_error const&) in ng.o
      boost::wrapexcept<std::length_error>::~wrapexcept() in ng.o
      boost::exception_detail::error_info_injector<std::length_error>::~error_info_injector() in ng.o
      ...
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ng] Error 1`

**Comment by UnkindPartition** [comment]
> `cc ng.o -o ng`

That's strange, it shouldn't do that.

Are you typing `make ng` instead of just `make` by any chance? You can also try `make ng.so` to make it a bit more explicit. Does it produce an `ng.so` file in the current directory?

**Comment by danliebke** [comment]
Yes, I was typing 'make ng'. Typing 'make' has produced an ng.so file. Thanks for your help.

**Comment by UnkindPartition** [comment]
Great!
